CREATE DATABASE UserVaultDB;

USE UserVaultDB;

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(150) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Sex NVARCHAR(6) CHECK (Sex IN ('Male', 'Female'))
);

CREATE TABLE CustomProperties (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE,
    Name NVARCHAR(150) NOT NULL,
    Value NVARCHAR(255) NOT NULL
);